---
title: "FinalProjectEconData"
author: "Zach"
date: "5/2/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Countries the US has been hostile towards, based on: 
gdp, life expectancy, gov debt, gini coefficient, literacy rate, years since hostily/ how long we were hostile with them

```{r}
library(tidyverse)
library(rvest)
library(httr)
```


```{r}
WikiPoverty<-read_html("https://en.wikipedia.org/wiki/List_of_countries_by_percentage_of_population_living_in_poverty")
PovertyNodes<-html_nodes(WikiPoverty, css = "table")
PovertyTable<-html_table(PovertyNodes, header =TRUE, fill = TRUE)[[1]]
# remove countries with n/a's?? only include on column?? add up columns?
Poverty <- PovertyTable%>%
  rename(lessthan_1.90= "< $1.90[4]",
         lessthan_3.20= "< $3.20[5]",
         lessthan_5.50= "< $5.50[6]")
PovertyTibble<-as_tibble(Poverty)

WikiTaxes<-read_html("https://en.wikipedia.org/wiki/List_of_countries_by_tax_rates")
TaxNodes<-html_nodes(WikiTaxes, css= "table")
TaxTable<-html_table(TaxNodes, header = TRUE, fill = TRUE)[[10]]
TaxTib<-as_tibble(TaxTable)
TaxTibble<-TaxTib%>%
  mutate(`Corporate tax`= str_replace_all(`Corporate tax`,"%.*", ""),
         `Income tax (minimum prevailing national + subnational rate)`= str_replace_all(`Income tax (minimum prevailing national + subnational rate)`,"%.*", ""),
         `Income tax (maximum prevailing national + subnational rate)[1]`= str_replace_all(`Income tax (maximum prevailing national + subnational rate)[1]`,"%.*", ""),
         `VAT or GST or sales tax`= str_replace_all(`VAT or GST or sales tax`,"%.*$", ""),
         Country= str_replace_all(Country,"(\\[.*\\]$)", ""))

# how to get rid of brackets and extra wording in values??

WikiPopulation<-read_html("https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)")
PopulationNodes<-html_nodes(WikiPopulation, css = "table")
PopulationTable<-html_table(PopulationNodes, header = TRUE, fill =TRUE)[[2]]
PopulationTib<-as_tibble(PopulationTable)
PopulationTibble<-PopulationTib%>%
  mutate(`Country or area`=str_replace_all(`Country or area`,"(\\[.*\\]$)", ""))%>%
  slice(2:n())%>%
  view
  

WikiMinimumWage<- read_html("https://en.wikipedia.org/wiki/List_of_minimum_wages_by_country")
WageNodes<- html_nodes(WikiMinimumWage, css="table")
WageTable<-html_table(WageNodes, header=TRUE, fill=TRUE)[[1]]
WageTib<-as_tibble(WageTable, .name_repair = "unique")
WageTibble<-WageTib%>%
  slice(2:n())


WikiAid<- read_html("https://en.wikipedia.org/wiki/United_States_foreign_aid")
AidNodes<- html_nodes(WikiAid, css="table")
AidTable<- html_table(AidNodes, header=TRUE, fill=TRUE)[[1]]
AidTibble<-as_tibble(AidTable)

WikiGDP<- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)")
GDPNodes<- html_nodes(WikiGDP, css="table")
GDPTable<- html_table(GDPNodes, header=TRUE, fill=TRUE)[[3]]
GDPTib<-as_tibble(GDPTable, .name_repair = "unique")
GDPTibble<-GDPTib%>%
  slice(2:n())%>%
  slice(-2)%>%
  mutate(`Country/Territory`= str_replace_all(`Country/Territory`,"(\\[.*\\]$)", ""))

WikiLife<- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_life_expectancy")
LifeNodes<- html_nodes(WikiLife, css="table")
LifeTable<- html_table(LifeNodes, header=TRUE, fill=TRUE)[[1]]
LifeTibble<-as_tibble(LifeTable)


WikiGini<-read_html("https://en.wikipedia.org/wiki/List_of_countries_by_income_equality")
GiniNodes<- html_nodes(WikiGini, css="table")
GiniTable<- html_table(GiniNodes, header=TRUE, fill=TRUE)[[2]]
GiniTib<-as_tibble(GiniTable, .rows = , .name_repair = "unique")
GiniTibble<-GiniTib%>%
  rename("WorldBankGini"= `World Bank Gini [3]...4`)%>%
  mutate(WorldBankGini= str_replace_all(WorldBankGini,"(..\\]$)", ""))%>%
  slice(3:n())
  #Code for later after joining
  

WikiLiteracy<- read_html("https://en.wikipedia.org/wiki/List_of_countries_by_literacy_rate")
LiteracyNodes<- html_nodes(WikiLiteracy, css="table")
LiteracyTable<- html_table(LiteracyNodes, header=FALSE, fill=TRUE)[[3]]
LiteracyTib<-as_tibble(LiteracyTable, .name_repair = "unique")
LiteracyTibble<-LiteracyTib%>%
  slice(-2)


world_data<- AidTibble%>%
  full_join(GDPTibble, c("Country"="Country/Territory"))%>%
  select(1:5, "GDP(US$million)")%>%
  full_join(PovertyTibble,c("Country"="Country"))%>%
  full_join(PopulationTibble, c("Country"="Country or area"))%>%
  full_join(LifeTibble, c("Country"="Country and regions"))%>%
  full_join(GiniTibble, c("Country"="Country"))%>%
  full_join(TaxTibble, c("Country"="Country"))%>%
  full_join(WageTibble, c("Country"= "Country"))%>%
  full_join(LiteracyTibble, c("Country"="X1"))
  
WorldTibble <- world_data %>%
    select(1:6, 9, 11, 16, 21, 23, 25, 28, 34, 40, 43, 47, 49, 51)%>%
    rename(YouthLitRate= "X2",
           AdultLitRate= "X4",
           ElderlyLitRate= "X6",
           EconomicMilitaryAssist= "Economic and Military Assistance FY 2017, $US millions",
           AidperCapita= "Aid received per capita FY 2017, $US",
           EconAssist= "Economic Assistance FY 2017, $US millions",
           MilitaryAssist= "Military Assistance FY2017, $US millions",
           GiniCoef= "WorldBankGini",
           AnnualMinWage= "Annual...3",
           HourlyMinWage= "Hourly...6")







    MaleFemaleLifeExp= "Both sexes lifeexpectancy(HALE)"
Population= 9

DRCTib<-WorldTibble%>%
  mutate(Country = ifelse(Country %in% c("Congo (Kinshasha)", "Congo, Dem. Republic", "Congo, Democratic Republic of the", "Democratic Republic of the Congo", "DR Congo", "Congo, Dem. Rep."), "DRC", Country))%>%
  filter(Country == "DRC")%>%
  fill(everything() , .direction="up")%>%
  slice(1)%>%
  view

TrueWorldTib<-rbind(DRCTib, WorldTibble)

AidWorldTib<-TrueWorldTib%>%
  filter(!is.na(EconomicMilitaryAssist))%>%
  slice(-22)


```
