---
title: "MapsTest"
author: "Zach and Natalie"
date: "5/9/2019"
DisplayMode: Showcase
Type: Shiny
Output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE}
library(tidyverse)
library(rvest)
library(httr)
library(shiny)
library(ggplot2)
library(maps)
library(readr)
library(dplyr)
```

```{r}
AidWorldTib <- read.csv("~/Mscs 264 S19/Inclass/AidWorldTib.csv")%>%
  select(-X,-`GDP.US.million.`, -`Corporate.tax`, -AnnualMinWage)%>%
  group_by(Country)%>%
  mutate(TotalLiteracy = (sum(YouthLitRate, AdultLitRate, ElderlyLitRate, na.rm =TRUE))/3)%>%
  ungroup%>%
  mutate(OverAverageLit = ifelse(TotalLiteracy>= 91, "Yes", "No"),
         OverAverageLife = ifelse(`Both.sexes.lifeexpectancy..HALE.`>=71.5, "Yes", "No"),
         OverAveragePoverty = ifelse(PercentPoverty>=35, "Yes", "No"),
         EconAidPerCapita = (EconAssist*1000000/Population),
         MilAidPerCapita = (MilitaryAssist*1000000/Population))%>%
  rename("TotalExpectancy" = `Both.sexes.lifeexpectancy..HALE.`,
         "FemaleExpectancy"= `Female.life.expectancy`,
         "MaleExpectancy" = `Male.life.expectancy`)

world <- map_data("world")%>% 
  rename(place = region)%>%
  mutate(place = ifelse(place == "Democratic Republic of the Congo", "DRC", place))

aidmapdata<- right_join(AidWorldTib, world, by = c("Country" = "place"))


totaloutlier<-AidWorldTib%>%
  filter(AidperCapita >100)



outlier<- AidWorldTib%>%
  filter(EconAidPerCapita>100 | MilAidPerCapita >100 | AidperCapita >100)


```

```{r}
mainPanel(
  fluidRow("For our project we wanted to explore the qualities of countries that US foreign aid is provided to. Our main reasoning behind this is that the term 'foreign aid' is often misunderstood and over generalized. While the United States provides a great amount of material aid and personnel aid around the world, we often forget that direct monetary compensation does make up a degree of our comitments as well. Overall, we examined how a vareity of social and economic factors are impacted by the amount of foreign aid the US provided, broken down by total, military, and economic aid. To accomplish this, we used the rvest and httr packages to scrape, and tidyverse, ggplot2, maps, readr, dplyr, and shiny to visualize the data. We pulled all our data off of wikipedia, and have linked the websites below.")
)
titlePanel("Aid per country")

inputPanel(selectInput("y", label= "y-axis variable:",
           choices= c("Total Aid"= "EconomicMilitaryAssist",
                         "Economic Aid"= "EconAssist",
                         "Military Aid"="MilitaryAssist",
                         "Aid per Capita"= "AidperCapita"))
)

renderPlot({
  ggplot(AidWorldTib, mapping = aes_string(x='Country', y= input$y))+
    geom_col(aes(fill = Continent))+
    theme(axis.text.x = element_text(angle = 90, hjust = 1))
})

mainPanel(
  fluidRow("This plot helps visualize how much Economic and Military Aid countries recieve from the US. It also displays combined military and economic and combine military and economic aid per capita. The bars are colored by contitent to help visualize where US monetary aid goes.")
)


titlePanel("World Map")
renderPlot({
  ggplot() + 
  geom_polygon(data = aidmapdata, aes_string(x='long', y = 'lat', group = 'group', fill = input$y)) + 
  coord_fixed(1.3) +
    labs(x= "Longitude",
         y= "Latitude")
}
)

titlePanel("Type of Aid vs. Life Expectancy")

inputPanel(selectInput("YAxis", "Social Indicator:",
           choices= c("Female Life Expectancy"= "FemaleExpectancy",
                         "Male Life Expectancy"= "MaleExpectancy",
                      "Total Life Expectancy"= "TotalExpectancy"
                         )))
inputPanel(selectInput("XAxis", "Type of Aid:",
           choices= c("Economic Aid per Capita"= "EconAidPerCapita",
                         "Military Aid per Capita"="MilAidPerCapita",
                         "Total Aid per Capita"= "AidperCapita")))
renderPlot({
  ggplot(AidWorldTib, aes_string(x= input$XAxis, y = input$YAxis))+
    geom_point(aes(color = Continent))+
    labs(x= "Type of Aid per Capita",
         y= "Social Indicator")
})
mainPanel("This graph displays life expectancies for Males, Females, and both genders when considering the different aids per capita. We were interesed in looking at life expectancy and aid to see if there was a relationship with how much aid countries recieve and their life expectancy.")

titlePanel("Aid per Country vs. Economic Indicators")

inputPanel(selectInput("YAxis2", "Economic Indicator:",
           choices= c("GDP in US Millions"= "GDP",
                         "Gini Coefficient"= "GiniCoef",
                         "Hourly Minimum Wage"="HourlyMinWage"
                         )))
inputPanel(selectInput("XAxis2", "Type of Aid:",

           choices= c("Economic Aid per Capita"= "EconAidPerCapita",
                         "Military Aid per Capita"="MilAidPerCapita",
                         "Total Aid per Capita"= "AidperCapita")))
mainPanel(
  fluidRow("We decided to use per capita aid as the standard method of looking at foreign aid. Our primary motivation for was the standard economic practice to measure certain monetary indicators per capita, as it allows comparison among countries. Beyond that it allows us to get a better idea of the scope of the impact the aid is having in the country." 
  ))
renderPlot({
  ggplot(AidWorldTib, aes_string(x= input$XAxis2, y = input$YAxis2))+
    geom_point(aes(color = Continent))+
    geom_text(aes(label = Country), data = outlier)+
    labs(x= "Type of Aid per Capita",
         y= "Economic Indicator")
    })



titlePanel("Social Indicators vs. Type of Aid")

inputPanel(selectInput("YAxis3", "Type of Aid:",
           choices= c("Economic Aid per Capita"= "EconAidPerCapita",
                         "Military Aid per Capita"="MilAidPerCapita",
                         "Total Aid per Capita"= "AidperCapita"
                         )))
inputPanel(selectInput("XAxis3", "Social Indicator:",
           choices= c("Above Average Literacy Rate?"= "OverAverageLit",
                         "Above Average Life Expectancy?"="OverAverageLife",
                         "Above Average Poverty Rate?"= "OverAveragePoverty")))
renderPlot({
  ggplot(AidWorldTib, aes_string(x= input$XAxis3, y = input$YAxis3))+
    geom_boxplot()+
    labs(x= "Above Average?",
         y= "Selected Aid per Capita")
})

mainPanel(
fluidRow("Above Average Literacy Rate? displays whether the country is above or below the global literacy rate, which is 91%."), 
fluidRow("Above Average Life Expectancy Rate? displays whether or not a country is above the global average of the life expectancy rate. Out of all the contries that recieve funding, only one country, Isreal, is above the life expectancy rate and they only recieve Military Aid, not Economic Aid."),
fluidRow("Above Average Poverty Rate? displays whether or not a country is above"))


```

