---
title: "ProjectTest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
library(httr)
library(rvest)
library(stringr)
```


```{r}
nytimesAPI<-"dZEgsuBIgwiDwmOrfYTAVMNlHwopNjGv"

nytimesURL<- str_c("https://api.nytimes.com/svc/search/v2/articlesearch.json?facet_field=day_of_week&facet=true&begin_date=20161001&end_date=20161031&api-key=", nytimesAPI)

NyTimes<-tibble(url=character(), headline = character())

url <- str_c("http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_per/.json?fields=pages,links,scope_notes&apikey=", nytimesAPI)
  nytimesGET <- GET(nytimesURL)
  details <- content(nytimesGET, "parse")
  betterdetails<-unlist(details$response$docs)
  view(betterdetails)
  
for(j in 1:10) {
  url <- str_c("http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_per/.json?fields=pages,links,scope_notes&apikey=", nytimesAPI)
  nytimesGET <- GET(nytimesURL)
  details <- content(nytimesGET, "parse")
  snippets<- details$reponses$docs[[j]]$snippet
}
snippets


for(i in 1:2) {
  url <- str_c("http://api.nytimes.com/svc/semantic/v2/concept/name/nytd_per/.json?fields=pages,links,scope_notes&apikey=", nytimesAPI)
  nytimesGET <- GET(nytimesURL)
  details <- content(nytimesGET, "parse")
  NyTimes[i,1] <- details$response$docs$web_url
  NyTimes[i,2] <- details$response$docs$snippet
}
```

